terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.60.0"
    }
  }

  # backend "s3" is generated by Terragrunt (terraform/root.hcl -> backend.tf).
}

# provider "aws" is generated by Terragrunt (terraform/root.hcl -> provider_aws.tf).
