terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.60.0"
    }
  }
  # backend "s3" is generated by Terragrunt (terraform/root.hcl -> backend.tf).
}

# The aws provider here is NOT the Terragrunt-generated one (that is disabled for
# the runner layer in root.hcl): its default_tags read local.network.environment
# from the network remote_state, and the runner has no common_tags local.
provider "aws" {
  region = var.region

  default_tags {
    tags = {
      Project     = var.project
      Environment = local.network.environment
      ManagedBy   = "terraform"
    }
  }
}
